name: flutter_application_6
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stop_watch_timer: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:

  uses-material-design: true
  fonts:
    - family: EBGaramond
      fonts:
        - asset: fonts/EBGaramond-SemiBoldItalic.ttf